name = "ddt-backend-worker"
main = "src/index.js"
compatibility_date = "2026-01-01"

[build]
command = "npm install"

[[d1_databases]]
binding = "DB"
database_name = "ddt-database"
database_id = "6f9f2d07-264b-43e6-9edf-ffd01c89f314"